end_point = "http://127.0.0.1:5000"
post_url = end_point + "/v1/books/manipulation"
put_url = end_point + "/v1/books/manipulation"
get_info_url = end_point + "/v1/books/info"
get_latest_url = end_point + "/v1/books/latest"
get_ids_url = end_point + "/v1/books/ids"
get_manipulation_url = end_point + "/v1/books/manipulation"
delete_url = end_point + "/v1/books/manipulation"
